[build]
  command = "npm run build:netlify"
  publish = "dist"
  # Ignore build command for dependabot PRs and content-only changes
  ignore = "git log -1 --pretty=%B | grep -q '^dependabot' || git diff HEAD^ HEAD --quiet -- ':!src/content/'"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_SITE_ID = "5a20ec24-b427-4971-a742-f3f5c443143e"
  # Production optimizations
  NODE_ENV = "production"
  # Enable Astro's production optimizations
  ASTRO_TELEMETRY_DISABLED = "1"
  # Reduce npm install time
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  # Cache directory for npm
  NPM_CONFIG_CACHE = "/opt/build/cache/.npm"

# Local Astro cache plugin
[[plugins]]
  package = "./netlify/plugins/astro-cache-plugin"

# Removed @netlify/plugin-sitemap - using Astro's sitemap integration instead

[dev]
  command = "npm run dev"
  port = 4321

# Netlify automatically handles trailing slashes based on pretty URLs
# This ensures URLs without trailing slashes redirect to ones with trailing slashes
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# ============================================================================
# SUBDOMAIN REDIRECTS
# ============================================================================
# Redirect language subdomains to their respective language paths

# Dutch subdomain redirects
[[redirects]]
  from = "https://nl.cro.cafe/"
  to = "https://cro.cafe/nl/"
  status = 301
  force = true

[[redirects]]
  from = "https://nl.cro.cafe/*"
  to = "https://cro.cafe/nl/:splat"
  status = 301
  force = true

# German subdomain redirects  
[[redirects]]
  from = "https://de.cro.cafe/"
  to = "https://cro.cafe/de/"
  status = 301
  force = true

[[redirects]]
  from = "https://de.cro.cafe/*"
  to = "https://cro.cafe/de/:splat"
  status = 301
  force = true

# Spanish subdomain redirects
[[redirects]]
  from = "https://es.cro.cafe/"
  to = "https://cro.cafe/es/"
  status = 301
  force = true

[[redirects]]
  from = "https://es.cro.cafe/*"
  to = "https://cro.cafe/es/:splat"
  status = 301
  force = true

# ============================================================================
# WEBFLOW TO ASTRO MIGRATION REDIRECTS
# ============================================================================

# Main section redirects
[[redirects]]
  from = "/podcast"
  to = "/en/episodes/"
  status = 301

[[redirects]]
  from = "/podcast/*"
  to = "/en/episodes/"
  status = 301

[[redirects]]
  from = "/guest"
  to = "/en/guests/"
  status = 301

[[redirects]]
  from = "/guest/*"
  to = "/all/guests/"
  status = 301

# Events and Books pages removed - redirect to about
[[redirects]]
  from = "/event"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/event/*"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/events"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/events/*"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/book"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/book/*"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/books"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/books/*"
  to = "/about/"
  status = 301

# ============================================================================
# LANGUAGE-SPECIFIC PATH REDIRECTS
# ============================================================================

# Dutch paths
[[redirects]]
  from = "/nl/podcast"
  to = "/nl/episodes/"
  status = 301

[[redirects]]
  from = "/nl/podcast/*"
  to = "/nl/episodes/"
  status = 301

[[redirects]]
  from = "/nl/guest"
  to = "/nl/guests/"
  status = 301

[[redirects]]
  from = "/nl/guest/*"
  to = "/guests/:splat"
  status = 301

[[redirects]]
  from = "/nl/event"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/nl/events"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/nl/book"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/nl/books"
  to = "/about/"
  status = 301

# German paths
[[redirects]]
  from = "/de/podcast"
  to = "/de/episodes/"
  status = 301

[[redirects]]
  from = "/de/podcast/*"
  to = "/de/episodes/"
  status = 301

[[redirects]]
  from = "/de/guest"
  to = "/de/guests/"
  status = 301

[[redirects]]
  from = "/de/guest/*"
  to = "/guests/:splat"
  status = 301

[[redirects]]
  from = "/de/event"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/de/events"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/de/book"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/de/books"
  to = "/about/"
  status = 301

# Spanish paths
[[redirects]]
  from = "/es/podcast"
  to = "/es/episodes/"
  status = 301

[[redirects]]
  from = "/es/podcast/*"
  to = "/es/episodes/"
  status = 301

[[redirects]]
  from = "/es/guest"
  to = "/es/guests/"
  status = 301

[[redirects]]
  from = "/es/guest/*"
  to = "/guests/:splat"
  status = 301

[[redirects]]
  from = "/es/event"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/es/events"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/es/book"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/es/books"
  to = "/about/"
  status = 301

# ============================================================================
# COMMON VARIATIONS AND SEO REDIRECTS
# ============================================================================

[[redirects]]
  from = "/shows"
  to = "/en/episodes/"
  status = 301

[[redirects]]
  from = "/podcasts"
  to = "/en/episodes/"
  status = 301

[[redirects]]
  from = "/episodes"
  to = "/en/episodes/"
  status = 301

[[redirects]]
  from = "/guests"
  to = "/all/guests/"
  status = 301

[[redirects]]
  from = "/host"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/hosts"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/about-us"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/team"
  to = "/about/"
  status = 301

# Newsletter/subscription variations
[[redirects]]
  from = "/newsletter"
  to = "/en/subscribe/"
  status = 301

[[redirects]]
  from = "/signup"
  to = "/en/subscribe/"
  status = 301

# Privacy and legal
[[redirects]]
  from = "/privacy"
  to = "/privacy-policy/"
  status = 301

[[redirects]]
  from = "/terms"
  to = "/terms-of-service/"
  status = 301

[[redirects]]
  from = "/legal"
  to = "/privacy-policy/"
  status = 301

# Search variations
[[redirects]]
  from = "/find"
  to = "/search/"
  status = 301

[[redirects]]
  from = "/search-episodes"
  to = "/search/"
  status = 301

[[redirects]]
  from = "/search-guests"
  to = "/search/"
  status = 301

# Common typos and variations
[[redirects]]
  from = "/podcast-episodes"
  to = "/en/episodes/"
  status = 301

[[redirects]]
  from = "/all-episodes"
  to = "/all/episodes/"
  status = 301

[[redirects]]
  from = "/all-guests"
  to = "/all/guests/"
  status = 301

[[redirects]]
  from = "/guest-profiles"
  to = "/all/guests/"
  status = 301

[[redirects]]
  from = "/speaker"
  to = "/all/guests/"
  status = 301

[[redirects]]
  from = "/speakers"
  to = "/all/guests/"
  status = 301

# ============================================================================
# WEBFLOW-SPECIFIC LEGACY PATHS
# ============================================================================

[[redirects]]
  from = "/blog"
  to = "/en/episodes/"
  status = 301

[[redirects]]
  from = "/blog/*"
  to = "/en/episodes/"
  status = 301

[[redirects]]
  from = "/news"
  to = "/en/episodes/"
  status = 301

[[redirects]]
  from = "/news/*"
  to = "/en/episodes/"
  status = 301

[[redirects]]
  from = "/resources"
  to = "/en/episodes/"
  status = 301

[[redirects]]
  from = "/resources/*"
  to = "/en/episodes/"
  status = 301

# Webflow forms and dynamic content
[[redirects]]
  from = "/forms/*"
  to = "/en/subscribe/"
  status = 301

[[redirects]]
  from = "/thank-you"
  to = "/en/subscribe/"
  status = 301

[[redirects]]
  from = "/thanks"
  to = "/en/subscribe/"
  status = 301

[[redirects]]
  from = "/success"
  to = "/en/subscribe/"
  status = 301

# Catch-all for old Webflow paths
[[redirects]]
  from = "/w/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/cms/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/collection/*"
  to = "/all/episodes/"
  status = 301

# ============================================================================
# RSS FEED REDIRECTS
# ============================================================================

[[redirects]]
  from = "/feed.xml"
  to = "https://feeds.transistor.fm/cro-cafe"
  status = 301

[[redirects]]
  from = "/rss"
  to = "https://feeds.transistor.fm/cro-cafe"
  status = 301

[[redirects]]
  from = "/feeds"
  to = "https://feeds.transistor.fm/cro-cafe"
  status = 301

[[redirects]]
  from = "/rss.xml"
  to = "https://feeds.transistor.fm/cro-cafe"
  status = 301

# ============================================================================
# SOCIAL MEDIA REDIRECTS
# ============================================================================

[[redirects]]
  from = "/linkedin"
  to = "https://linkedin.com/company/cro-cafe"
  status = 301

[[redirects]]
  from = "/twitter"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/youtube"
  to = "https://youtube.com/@crocafe"
  status = 301

# ============================================================================
# SPECIFIC GUEST PROFILE REDIRECTS
# ============================================================================
# These guests exist and need proper redirects

[[redirects]]
  from = "/guest/sander-volbeda"
  to = "/guests/sander-volbeda/"
  status = 301

[[redirects]]
  from = "/guest/craig-sullivan"
  to = "/guests/craig-sullivan/"
  status = 301

[[redirects]]
  from = "/guest/peep-laja"
  to = "/guests/peep-laja/"
  status = 301

[[redirects]]
  from = "/guest/tim-ash"
  to = "/guests/tim-ash/"
  status = 301